# Generated by Django 2.2.5 on 2020-01-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=6)),
                ('contact_no', models.BigIntegerField()),
                ('parent_contact', models.BigIntegerField()),
                ('college_name', models.TextField()),
                ('branch_name', models.TextField()),
                ('stream_name', models.TextField()),
                ('current_year', models.DateField()),
            ],
        ),
    ]
