# Generated by Django 3.0.2 on 2020-01-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='current_year',
            field=models.TextField(),
        ),
    ]
