# Generated by Django 3.0.2 on 2020-01-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200108_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentyear',
            name='current_year',
            field=models.CharField(max_length=50),
        ),
    ]
