# Generated by Django 3.0.2 on 2020-01-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_stream'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=70)),
                ('sem', models.IntegerField()),
                ('paper', models.IntegerField()),
                ('author_name', models.CharField(max_length=50)),
                ('book_edition', models.IntegerField()),
                ('barcode', models.BigIntegerField()),
                ('publisher', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('purchase_year', models.DateField()),
            ],
        ),
    ]
