# Generated by Django 3.0.2 on 2020-01-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='paper',
            field=models.IntegerField(default=None),
        ),
    ]
