# Generated by Django 3.0.2 on 2020-01-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20200112_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sem',
            field=models.IntegerField(default=None),
        ),
    ]
