# Generated by Django 3.0.2 on 2020-01-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20200112_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_edition',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
